name: base-env
channels:
  - bioconda
  - conda-forge
dependencies:
  - minimap2=2.14
  - pilon=1.22
  - canu=1.7.1
  - spades=3.12.0
  - fastqc=0.11.7
  - gnuplot=5.2.3
  - multiqc=1.6
  - quast=5.0
  - prinseq=0.20.4
  - ngmlr=0.2.7
  - sniffles=1.0.10
  - scipy=1.1.0
  - numpy=1.15.1
  - scikit-learn=0.19.2
  - tabix=0.2.5
  - mummer=3.23
#  - last=941
#  - kraken-all=0.10.6_eaf8fb68
