name: assembly-env
channels:
  - bioconda
  - conda-forge
dependencies:
  - minimap2=2.11
  - pilon=1.22
  - canu=1.7.1
  - spades=3.12.0
  - fastqc=0.11.7
  - gnuplot=5.2.3
  - multiqc=1.6
  - quast=5.0
  - prinseq=0.20.4
  - kraken-all=0.10.6_eaf8fb68
  - ngmlr=0.2.7
  - sniffles=1.0.8
  - nanoqc=0.7.0
